mod applemusic;
mod binilyrics;
mod genie;
mod kugou;
mod lrclib;
mod lrcmux;
mod lyricsovh;
mod netease;
mod qqmusic;
mod stixoi;

pub use applemusic::*;
pub use binilyrics::*;
pub use genie::*;
pub use kugou::*;
pub use lrclib::*;
pub use lrcmux::*;
pub use lyricsovh::*;
pub use netease::*;
pub use qqmusic::*;
pub use stixoi::*;
